services:
  freepbx-app:
    container_name: freepbx-app
    image: bndgzglln23/pibpx:latest
    volumes:
      - ./data/certs:/certs
      - ./data/data:/data
      - ./data/logs:/var/log
      - ./data/www:/var/www/html
      - ./data/db:/var/lib/mysql
      - ./data/var/www/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - HTTP_PORT=8099
      - HTTPS_PORT=8443
      - RTP_START=10000
      - RTP_FINISH=11000
      - DB_EMBEDDED=TRUE
      - DEBUG_MODE=FALSE
      - ENABLE_SSL=FALSE
      - ENABLE_FOP=FALSE
      - UCP_FIRST=TRUE
    restart: always
    ports:
      - "8099:8099"
      - "8443:8443"
      - "5060:5060/udp"
      - "5160:5160/udp"
      - "5061:5061"
      - "5161:5161"
      - "10000-10100:10000-10100/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
